Re-did pre-commit-config check
adafruit/adabot pull request #272
Opened 2022-06-17 21:35 UTC by evaherrada

The check now compares the files from cookecutter with the file in each repo

2022-06-18 02:44 UTC, tekktrik commented
If I understand how this works, this will conflict with https://github.com/adafruit/cookiecutter-adafruit-circuitpython/pull/186 which adds templated content to the YAML file.

2022-06-21 18:05 UTC, tekktrik commented
Both - mostly the inner ones, but also changes the upper one to remove the YAML check pre-commit hook because the inner ones aren't valid YAML files anymore

2022-06-21 18:19 UTC, tekktrik commented
Never mind, it's still an invalid file per the pre-commit hook at least

2022-06-21 18:23 UTC, evaherrada commented
Wait so are you saying it's all good and this won't conflict with the PR?

Also FWIW, the files changed in 186:
![Screenshot_2022-06-21_14-21-23](https://user-images.githubusercontent.com/33632497/174871211-b582dec3-6a0e-473f-bfab-507c845ed841.png)

2022-06-21 18:48 UTC, tekktrik commented
Sorry, it's not that it will conflict during the merge, but that the solution here means we can't template the file for cookiecutter as 186 does.  The YAML check will flag the YAML files after merging 186 because they aren't valid until after cookiecutter has run them.

2022-06-21 19:06 UTC, evaherrada commented
Ohhh I think I understand what you're saying. Basically that if we do it this way we won't be able to do things that were done in 186 (as in make it so cookiecutter can change the file when it is run) to the cookiecutter .pre-commit-config.yaml, right?

2022-06-21 19:06 UTC, tekktrik commented
Yup yup!

2022-06-21 19:21 UTC, evaherrada commented
Ok. In that case I think the way to do it would be to parse the file for the versions and set them to variables

2022-06-22 18:54 UTC, evaherrada commented
@tekktrik How does it look now? On the first run it parses the file from cookiecutter to get the versions and then does the same to the file in each library

2022-06-29 15:35 UTC, evaherrada commented
@tekktrik No, it's specifically looking at this one https://github.com/adafruit/cookiecutter-adafruit-circuitpython/blob/main/%7B%7B%20cookiecutter%20and%20'tmp_repo'%20%7D%7D/.pre-commit-config.yaml

2022-06-29 15:39 UTC, tekktrik commented
Got it, since that isn't templated it should be good!

2022-07-29 17:56 UTC, dhalbert commented
@tekktrik is this good to approve now? Not sure what state it's in.

2022-07-29 18:28 UTC, tekktrik requested changes
Thanks for pinging @dhalbert, one small change needed.

2022-07-29 18:28 UTC, tekktrik commented on adabot/lib/circuitpython_library_validators.py
> +                "circuitpython/main/%7B%7B%20cookiecutter%20and%20'tmp_repo'%20%7D"
This needs to be updated to the new link based on @jepler's modifications

2022-11-08 18:08 UTC, tekktrik commented
Drafting so this doesn't get merged before https://github.com/adafruit/cookiecutter-adafruit-circuitpython/pull/212

2022-11-08 19:59 UTC, kattni approved these changes
Looks good to me, did not test.

2022-11-08 19:59 UTC, merged